#+TITLE: Jinghui's emacs.d
#+AUTHOR: Jinghui Hu
#+EMAIL: hujinghui@buaa.edu.cn
#+DATE: <2026-09-10 Thu>
#+STARTUP: indent cache num inlineimages
#+TAGS: emacs configuration elisp


* Notes
1. Required Emacs version: 30.2 or later
2. =which-key=, =eglot=, =transient= and =use-package= ship with Emacs now, they
   are no longer installed from ELPA
3. Heavy packages are deferred, see *Loading strategy* below

* Install packages
The package list is =my-packages= in =lisp/init-package.el=. Both scripts drive
=scripts/instpkg.el=, which refreshes the archives and installs whatever is
missing.

Linux and macOS
#+BEGIN_SRC sh
  scripts/install-elpa-package.sh
#+END_SRC

Windows
#+BEGIN_SRC bat
  scripts\install-elpa-package.bat
#+END_SRC

The bat script finds =emacs.exe= on its own, picking the highest version under
=%ProgramFiles%\Emacs=. Override it with the =EMACS= environment variable, and
pass =-n= to print the command without running anything.

#+BEGIN_SRC bat
  set "EMACS=C:\Program Files\Emacs\emacs-31.1\bin\emacs.exe"
  scripts\install-elpa-package.bat -n
#+END_SRC

* Loading strategy
These are not loaded at startup, they arrive by autoload when a command runs or
a matching file is opened: =org=, =verb=, =tramp=, =rustic=, =magit=, =elfeed=,
=eglot=, =leetcode=, =dired=.

When adding config for such a package, keep plain =setq= at top level, and move
anything that touches a keymap, a face or a mode-specific variable into
=with-eval-after-load=. A bare =(require 'foo)= at top level pulls the whole
dependency tree in and costs startup time: =(require 'rustic)= alone used to
drag in =org= and =tramp=.

* Build EMACS from source
** Dependencies
Ubuntu
#+BEGIN_SRC shell
  sudo apt-get update && apt-get upgrade
  sudo apt-get install build-essential libncurses-dev autoconf make gcc \
       texinfo libgtk-3-dev libxpm-dev libjpeg-dev libgif-dev libtiff5-dev \
       libncurses5-dev libxml2-dev libgnutls28-dev
#+END_SRC

CentOS
#+BEGIN_SRC sh
  yum install -y libXpm-devel libtiff-devel gnutls-devel giflib-devel \
      libjpeg-turbo-devel ncurses-devel libpng-devel libXaw-devel texinfo
#+END_SRC

** Build and Install
#+BEGIN_SRC sh
  ./autogen.sh
  ./configure --prefix=/opt/emacs

  make -j 4
  make docs

  sudo make install && make install-doc
#+END_SRC

* Customize local config
Private settings go in *~/.emacs.local.el*, loaded after everything else, so it
can override any package config. *~/.emacs.pre.el* is loaded first instead, use
it for things that must be in place before packages initialize.

The following is an example.

#+BEGIN_SRC sh :results none
  touch ~/.emacs.local.el
#+END_SRC

#+BEGIN_SRC elisp
  ;; -----------------------------------------------------------------------------
  ;; startup initial frame
  ;; -----------------------------------------------------------------------------
  (setq initial-frame-alist
    '((tool-bar-lines . 0) (width . 120) (height . 36) (left . 800) (top . 350)))
  (setq default-frame-alist
    '((tool-bar-lines . 0) (width . 120) (height . 36) (left . 800) (top . 350)))
#+END_SRC

* Color display test
** Natural Colors
#+BEGIN_SRC css
  #320001 #333301 #333333 #670001
  #653332 #346667 #cccccc #656600
  #999999 #67999a #986665 #000000
#+END_SRC

** D3 Categorial
*** d3.schemeCategory10
#+BEGIN_SRC css
  #1776b6 #ff7f00 #24a222 #d8241f #9564bf #8d5649 #e574c3 #7f7f7f #bcbf00 #00bed1
#+END_SRC

*** d3.schemeAccent
#+BEGIN_SRC css
  #7fc97f #beaed4 #fdc086 #ffff99 #386cb0 #f0027f #bf5b17 #666666
#+END_SRC

* Download link for EMACS on Windows
   1. [[https://mirrors.tuna.tsinghua.edu.cn/gnu/emacs/windows/][emacs-windows-download tuna tsinghua]]
   2. [[http://mirrors.ustc.edu.cn/gnu/emacs/windows/][emacs-windows-download ustc]]
   3. [[http://mirror.hust.edu.cn/gnu/emacs/windows/][emacs-windows-download hust]]
